ip_network_part = "10.18.0."
clients_dir = "clients"
server_dir = "server"
pubkey_filename = "publickey"
privkey_filename = "privatekey"
endpoint_filename = "endpoint"
client_config_filename = "wg0-client.conf"